;-----------------------------------------------------------------------------
; logo.inc
; Part of penetrator, the zx spectrum game, made for Commodore Plus4
;
; Stefan Wessels, 2023
; This is free and unencumbered software released into the public domain.

;-----------------------------------------------------------------------------
.segment "TITLELUM"
.incbin "titlelum.lzh"

.segment "TITLECOL"
.incbin "titlecol.lzh"

.segment "TITLEGFX"
.incbin "titlegfx.lzh"
